name: OpenAPI generate decorated schema files

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  workflow_dispatch:
  pull_request:

jobs:
  generate-decorated-files:
    if: github.event.pull_request.user.login == 'github-openapi-bot'
    runs-on: ubuntu-latest
    steps:
      - name: Label pull requests with 'github-openapi-bot'
        uses: rachmari/labeler@832d42ec5523f3c6d46e8168de71cd54363e3e2e
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          add-labels: 'github-openapi-bot'
      - name: Checkout repository code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Install dependencies
        run: npm ci

      - name: Decorate the dereferenced OpenAPI schemas
        run: script/rest/update-files.js --decorate-only

      - name: Check in the decorated files
        uses: EndBug/add-and-commit@b3c7c1e078a023d75fb0bd326e02962575ce0519
        with:
          # The arguments for the `git add` command
          add: 'lib/rest/static/decorated'

          # The message for the commit
          message: 'Add decorated OpenAPI schema files'
