name: Lint workflows

# **What it does**: This lints our workflow files.
# **Why we have it**: We want some level of consistency in our workflow files.
# **Who does it impact**: Docs engineering.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  lint:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Run linter
        uses: cschleiden/actions-linter@0ff16d6ac5103cca6c92e6cbc922b646baaea5be
        with:
          workflows: '[".github/workflows/*.yml"]'
